import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import './globals.css';
import Image from 'next/image';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navLinkClass =
  'text-[#D4C9BE] no-underline font-medium py-2 transition-colors duration-200 hover:bg-[#123458] hover:text-[#F1EFEC]';
const btnClass =
  'bg-[#D4C9BE] text-[#123458] font-semibold px-6 py-2.5 rounded-full transition-colors duration-200 hover:bg-[#e0d8cd]';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('access_token');

  async function handleLogout() {
    'use server';

    const cookieStore = await cookies();
    cookieStore.delete('access_token');
    cookieStore.delete('_id');

    redirect('/');
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-brand-blue px-5 top-0 sticky z-999 shadow-[0_2px_10px_rgba(0,0,0,0.1)]">
          <div className="mx-auto max-w-300 flex justify-between items-center h-16 overflow-hidden">
            <div className="text-[#FCF8DD] flex items-center gap-1">
              <Image
                src="/logo3.png"
                alt="logo"
                width={200}
                height={200}
                className="w-14 h-auto rounded-lg"
                style={{ height: 'auto' }}
                priority
              />
              <h1 className="text-[1.5rem] font-bold">BlogApp</h1>
            </div>
            <nav>
              <ul className="flex list-none gap-8 items-center">
                <li>
                  <Link href="/" className={navLinkClass}>
                    Posts
                  </Link>
                </li>

                {!token && (
                  <>
                    <li>
                      <Link href="/login" className={navLinkClass}>
                        Login
                      </Link>
                    </li>
                    <li>
                      <Link href="/register" className={navLinkClass}>
                        Register
                      </Link>
                    </li>
                  </>
                )}

                {token && (
                  <>
                    <li>
                      <Link href="/post/create" className={navLinkClass}>
                        Create Post
                      </Link>
                    </li>
                    <li>
                      <form action={handleLogout}>
                        <button type="submit" className={btnClass}>
                          Logout
                        </button>
                      </form>
                    </li>
                  </>
                )}
              </ul>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
